# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InteractiveKeyboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InteractiveKeyboard
  pod 'NgKeyboardTracker'

  target 'InteractiveKeyboard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InteractiveKeyboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
